# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myuniquewebapp123

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myfrauddetection.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b86744090eab4861966de857725ac774 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_75cdacc426c1402d8a8b33b1a5a32381 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myfrauddetection.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b86744090eab4861966de857725ac774 }}/dockerimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myuniquewebapp123'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_94fdba17e15245459876e6ec5b773e90 }}
        images: 'myfrauddetection.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b86744090eab4861966de857725ac774 }}/dockerimage:${{ github.sha }}'
